### PR TITLE
Fixed test coverage badge

### LINKED ISSUE #184: Coveralls badge showing coverage as unknown
### Scenario/Intent
See the % of code coverage through the coveralls badge in the readme.

Apparently, according to coveralls documentation, what is missing is:
1. add `gem 'coveralls', require: false` to the gemfile
2. add `require coveralls` to the top of the spec_helper.rb file and add the following after the requires:
```ruby
Coveralls.wear!

SimpleCov.formatters = [
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
```

### Steps to Reproduce
Visit the [project github](https://github.com/HewlettPackard/oneview-sdk-ruby). Or look here:  [Coverage Status](https://coveralls.io/github/HewlettPackard/oneview-sdk-ruby?branch=master)

### Expected Result
The badge is up to date with the % of code covered

### Actual Result
 [Coverage Status](https://coveralls.io/github/HewlettPackard/oneview-sdk-ruby?branch=master)

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
Fixes the test coverage badge. Instead of using coveralls, this uses the built-in coverage capabilities of codeclimate.

### Issues Resolved
Fixes #184

### Check List
N/A

### CODE REVIEW

**Comment by ricardogpsf** [comment]
the badge for coverage should still "unknow" in here?

**Comment by jsmartt** [comment]
I think so. I believe it only shows the master branch's coverage, so it won't be updated until after the merge. @tmiotto can probably verify this, as we added this badge to the oneview Chef cookbook recently too.

**Comment by tmiotto** [comment]
Yep, code climate will only show the coverage for the default branch (in our case `master`) so it can be only shown when merged

**Comment by fgbulsoni** [comment]
For ruby, I'd actually prefer we use coveralls instead of code climate for coverage, as we actually have a lot of files being tested and coveralls provide a consolidated coverage dashboard for them and also it would be good to see the test coverage on each PR too

No problem using both, but I'd say coveralls would be better. :octocat:

**Comment by jsmartt** [comment]
Closing in favor of #191

**Pull request closed without merging**
