### PR TITLE
Preparing release 5.0.4

### PR DESCRIPTION
**Pull request by ricardogpsf**
### Description
Release 5.0.4

### Issues Resolved
N/A

### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [ ] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by fgbulsoni** [comment]
I'm assuming we want #270 merged before this, so why not just close this PR and add these small changes there?

**Comment by ricardogpsf** [comment]
@fgbulsoni may be, no problem for me. When #270 be done, I gonna put this code there, because some changes are being did yet.

**Comment by ricardogpsf** [comment]
Reopening this PR because this PR already was did over the changes of #270

**Comment by ricardogpsf** [comment]
Reopening this PR, because it already was did over changes of #270 and #270 was merged.

**Pull request closed without merging**
