### PR TITLE
Release PR

### PR DESCRIPTION
**Pull request by AsisBagga**
### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve. e.g., Fixes #01]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [ ] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Review by yuvirani — APPROVED** [review]

**Review by yuvirani — COMMENTED** [review]
Update version.rb file

**Comment by VenkateshRavula** [comment]
Update README versioning and also take care of connection_template in endpoints file

**Comment by AsisBagga** [comment]
> Update version.rb file

done

**Comment by AsisBagga** [comment]
> Update README versioning and also take care of connection_template in endpoints file

done

**Review by VenkateshRavula — APPROVED** [review]

**Pull request merged**
