### PR TITLE
Support CLI search with empty filter

### LINKED ISSUE #346: CLI - Search with empty filter
### Scenario/Intent
I would like to be able to show attributes for all ServerHardware (support `filter = {}`)

### Environment Details
 - **OneView SDK Version:** 5.4.0
 - **OneView Appliance Version:** All
 - **OneView Client API Version:** All
 - **Ruby Version:** All
 - **Platform:** All

### Steps to Reproduce
`$ oneview-sdk-ruby search ServerHardware -a serialNumber`

### Expected Result
Show all ServerHardware serial numbers

### Actual Result
Error: No value provided for required options '--filter'

### PR DESCRIPTION
**Pull request by jsmartt**
### Description
Support CLI search with empty filters

### Issues Resolved
Fixes #346

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (`$ rake test`).
- [x] New functionality has been documented in the README if applicable.
  - [x] New functionality has been thoroughly documented in the examples (please include helpful comments).
- [x] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG.

### CODE REVIEW

**Comment by soodpr** [comment]
@jsmartt - Thanks Jared for the contribution. I think we should update the README.md file as well to include this example which works without filter in the CLI section.

**Comment by jsmartt** [comment]
Done :)

**Comment by jsmartt** [comment]
Hi @sijeesh, yeah, the list command would be another fine place to put this functionality. It doesn't currently support showing specific attributes, so I put it in the search command because it was easier, but if you'd prefer me to add the option to show specific attributes in the list command, I can do that also.

**Comment by jsmartt** [comment]
I've created PR https://github.com/HewlettPackard/oneview-sdk-ruby/pull/348 with a better option to support the functionality I'm looking for. Closing this for now

**Pull request closed without merging**
